version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/SE-LAB
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
     - "27017:27017"